on:
  push:
  schedule:
    - cron: "0 * * * *"

jobs:
  external_info:
    runs-on: ubuntu-latest
    name: Get external info

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Get Medium Blogs
      uses: gautamkrishnar/blog-post-workflow@master
      with:
        comment_tag_name: MEDIUM
        max_post_count: "5"
        template: $randomEmoji
        feed_list: "https://medium.com/feed/@franciscofoz"

   
